<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.smartdata</groupId>
        <artifactId>smartdata-project</artifactId>
        <version>2.2.0-SNAPSHOT</version>
    </parent>

    <groupId>org.smartdata</groupId>
    <artifactId>smart-tests</artifactId>
    <name>smart-tests</name>
    <description>SSM System Tests</description>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <allure-maven.version>2.10.0</allure-maven.version>
        <allure.results.directory>${project.build.directory}/allure-results</allure.results.directory>
        <aspectj.version>1.9.22.1</aspectj.version>
        <spring-boot.version>2.7.18</spring-boot.version>
        <maven.surefire.version>3.5.2</maven.surefire.version>
        <maven.compiler.version>3.14.0</maven.compiler.version>
        <maven-resource-plugin.version>3.3.1</maven-resource-plugin.version>
        <java-test-common.version>1.9-jdk8</java-test-common.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.arenadata</groupId>
                <artifactId>java-test-common-jdk8</artifactId>
                <version>${java-test-common.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.arenadata</groupId>
            <artifactId>java-test-common-jdk8</artifactId>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>web-tests</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${maven.surefire.version}</version>
                        <configuration>
                            <skipTests>false</skipTests>
                            <goal>verify</goal>
                            <parallel>none</parallel>
                            <testFailureIgnore>false</testFailureIgnore>
                            <systemPropertyVariables>
                                <allure.results.directory>${allure.results.directory}</allure.results.directory>
                                <COMPOSE_FILE_NAME>target/test-classes/env/docker-compose.yaml</COMPOSE_FILE_NAME>
                                <useSystemClassLoader>true</useSystemClassLoader>
                            </systemPropertyVariables>
                            <argLine>
                                -ea -Xmx4G -XX:MaxMetaspaceSize=2G
                                -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                            </argLine>
                            <suiteXmlFiles>
                                <suiteXmlFile>src/test/resources/web-tests.xml</suiteXmlFile>
                            </suiteXmlFiles>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>org.aspectj</groupId>
                                <artifactId>aspectjweaver</artifactId>
                                <version>${aspectj.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.apache.maven.surefire</groupId>
                                <artifactId>surefire-testng</artifactId>
                                <version>${maven.surefire.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.4</version>
                <configuration>
                    <groupId>io.arenadata</groupId>
                    <artifactId>java-test-common-jdk8</artifactId>
                    <packaging>jar</packaging>
                    <file>${basedir}/lib/java-test-common-jdk8-${java-test-common.version}.jar</file>
                    <generatePom>false</generatePom>
                </configuration>
                <executions>
                    <execution>
                        <id>install-jar-lib</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven-resource-plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/test-classes/env/multihost</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>../supports/tools/docker/multihost/</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>io.arenadata</groupId>
                                    <artifactId>java-test-common-jdk8</artifactId>
                                    <version>${java-test-common.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/common-resources</outputDirectory>
                                    <excludes>io/**,META-INF/**,application.yaml</excludes>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${project.build.directory}/wars</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <dependencies>
                </dependencies>
                <configuration>
                    <skipTests>true</skipTests>
                    <parallel>none</parallel>
                    <testFailureIgnore>false</testFailureIgnore>
                    <systemPropertyVariables>
                        <allure.results.directory>${allure.results.directory}</allure.results.directory>
                    </systemPropertyVariables>
                    <argLine>
                        -ea -Xmx4G -XX:MaxMetaspaceSize=2G
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>${allure-maven.version}</version>
                <configuration>
                    <reportVersion>${allure-maven.version}</reportVersion>
                </configuration>
            </plugin>
        </plugins>

        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
            <testResource>
                <directory>target/common-resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
    </build>

</project>