get:
  tags:
    - Actions
  summary: Get action by id
  operationId: getAction
  parameters:
    - $ref: '../parameters/common/id.yaml'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../schemas/actions/Action.yaml'
    '404':
      description: Action with specified id not found
    '401':
      description: Unauthorized
