generate_data:
	bash ./generate_data.sh

delete_data:
	bash ./delete_data.sh

run_distcp:
	bash ./perf_test_distcp.sh

run_ssm_initial_sync:
	bash ./perf_test_ssm_initial_sync.sh

run_ssm_async_sync:
	bash perf_test_ssm_async_sync.sh