FROM quay.io/centos/centos:stream9

EXPOSE 749 88/udp

RUN yum install -y krb5-server

ENV REALM ${REALM:-DEMO}
ENV MASTER_PASSWORD ${MASTER_PASSWORD:-masterpassword}
ENV KADMIN_PRINCIPAL ${KADMIN_PRINCIPAL:-kadmin/admin}
ENV KADMIN_PASSWORD ${KADMIN_PASSWORD:-adminpassword}

CMD bash /tmp/kdc-init.sh
