springdoc:
  api-docs:
    path: /openapi-spec
  swagger-ui:
    url: /ssm-api.yaml
    disable-swagger-default-url: true
server:
  servlet:
    session:
      cookie:
        name: SSM_SESSION_ID
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
spring:
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
          cache-private: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
