- name: Check if jars are already copied for this host
  set_fact:
    jars_copied: "{{ hostvars[inventory_hostname].jars_copied | default(false) }}"

- name: "Stop {{ ssm_service_name }}"
  become: yes
  ansible.builtin.systemd_service:
    name: "{{ ssm_service_name }}.service"
    state: stopped

- block:

  - name: Remove old SSM jars
    become: yes
    ansible.builtin.file:
      path: /usr/lib/ssm/lib/
      state: absent

  - name: Ensures /usr/lib/ssm/lib/dir exists
    become: yes
    file:
      path: "/usr/lib/ssm/lib/"
      state: directory
      recurse: yes
      mode: u=rwx,g=rx,o=rx

  - name: Unarchive SSM distribution
    become: yes
    unarchive:
      src: "../smart-dist/target/smart-data-{{ ssm_version }}.tar.gz"
      dest: "/usr/lib/ssm/lib/"
      include:
        - "smart-data-{{ ssm_version }}/lib"
      extra_opts:
       - --strip-components=2

  - name: Mark jars already copied for this host
    set_fact:
      jars_copied: true

  when: not jars_copied

- name: "Start {{ ssm_service_name }}"
  become: yes
  ansible.builtin.systemd_service:
    name: "{{ ssm_service_name }}.service"
    state: started
